# Cruis'n Collection - one-time setup / health check.
# Run: right-click -> Run with PowerShell (no admin needed).
# Re-run any time; it only fixes what's missing.
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
Write-Host "== Cruis'n Collection setup ==" -ForegroundColor Cyan

function Fail($msg) { Write-Host "  [X] $msg" -ForegroundColor Red; $script:bad = $true }
function Ok($msg)   { Write-Host "  [ok] $msg" -ForegroundColor Green }

# --- 1. Python ---------------------------------------------------------------
$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { Fail "Python not found - install from python.org (check 'Add to PATH')" }
else {
    $v = & python -c "import sys; print('%d.%d' % sys.version_info[:2])"
    Ok "Python $v at $($py.Source)"
    Write-Host "  installing/verifying packages (numpy pillow moderngl glfw)..."
    & python -m pip install --quiet numpy pillow moderngl glfw
    Ok "Python packages ready"
}

# --- 2. vunit.exe ------------------------------------------------------------
$vunit = $env:CRUISN_VUNIT
if (-not $vunit) { $vunit = "E:\Source\mame-src\vunit.exe" }
if (-not (Test-Path $vunit)) {
    $ans = Read-Host "Path to vunit.exe (Enter to skip)"
    if ($ans) { $vunit = $ans }
}
if (Test-Path $vunit) { Ok "vunit.exe: $vunit" }
else { Fail "vunit.exe not found - build it per docs/INSTALL.md (developer section)" }

# --- 3. ROMs -----------------------------------------------------------------
$roms = $env:CRUISN_ROMS
if (-not $roms) { $roms = Join-Path $root "roms" }
if (-not (Test-Path (Join-Path $roms "crusnusa.zip"))) {
    $ans = Read-Host "Directory containing your ROM zips (Enter for $roms)"
    if ($ans) { $roms = $ans }
}
$have = @(); $miss = @()
foreach ($r in "crusnusa", "crusnwld", "offroadc", "crusnexo") {
    if ((Test-Path (Join-Path $roms "$r.zip")) -or (Test-Path (Join-Path $roms "$r.7z")) -or (Test-Path (Join-Path $roms $r))) { $have += $r } else { $miss += $r }
}
if ($have) { Ok ("ROMs found: " + ($have -join ", ")) }
if ($miss) { Write-Host "  [!] missing (games will be absent/fail): $($miss -join ', ')" -ForegroundColor Yellow }
if (-not $have) { Fail "no ROM sets found in $roms" }

# --- 4. FFB plugin (optional) ------------------------------------------------
if (Test-Path $vunit) {
    $vdir = Split-Path $vunit
    $ffb = @("dinput8.dll", "SDL2.dll", "MAME64.dll", "FFBPlugin.ini")
    $missing = $ffb | Where-Object { -not (Test-Path (Join-Path $vdir $_)) }
    if (-not $missing) { Ok "FFB Arcade Plugin present beside vunit.exe" }
    else {
        Write-Host "  [!] FFB plugin files missing beside vunit.exe: $($missing -join ', ')" -ForegroundColor Yellow
        Write-Host "      (wheel force feedback disabled - see docs/INSTALL.md; get the plugin"
        Write-Host "       from github.com/Boomslangnz/FFBArcadePlugin - ALL FOUR files needed)"
    }
}

# --- 5. write the launcher bat ----------------------------------------------
$bat = Join-Path $root "CruisnCollection.bat"
@"
@echo off
REM generated by setup.ps1 - safe to re-run setup to regenerate
set CRUISN_VUNIT=$vunit
set CRUISN_ROMS=$roms
cd /d "$root"
start "Cruisn Collection" /min python harness\collection.py %*
"@ | Set-Content -Encoding ascii $bat
Ok "launcher written: $bat"

if ($bad) {
    Write-Host "`nSetup finished WITH ISSUES - fix the [X] items above and re-run." -ForegroundColor Yellow
} else {
    Write-Host "`nAll good. Double-click CruisnCollection.bat to play." -ForegroundColor Cyan
}
Read-Host "Press Enter to close"
