"""Generate midvunit_menu_assets.h - pre-rendered A8 label bitmaps for the
in-game Esc options menu (the C++ overlay has no font engine). Rerun after
changing MENU_LABELS:

    python harness/gen_menu_assets.py
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HEADER = r"E:\Source\mame-src\src\mame\midway\midvunit_menu_assets.h"

MENU_LABELS = {
    "TITLE":   "OPTIONS",
    "RESUME":  "RESUME",
    "CRT_ON":  "CRT EFFECTS:  ON",
    "CRT_OFF": "CRT EFFECTS:  OFF",
    "EXIT":    "EXIT TO LAUNCHER",
    "HINT":    "UP / DOWN  SELECT      ENTER  OK      ESC  RESUME",
}
SIZES = {"TITLE": 64, "HINT": 24}


def render(text, px):
    try:
        font = ImageFont.truetype(r"C:\Windows\Fonts\bahnschrift.ttf", px)
    except OSError:
        font = ImageFont.load_default()
    box = font.getbbox(text)
    w, h = box[2] - box[0] + 8, box[3] - box[1] + 8
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((4 - box[0], 4 - box[1]), text, font=font,
                             fill=255)
    return img


def main():
    out = ["// GENERATED by cruisn-collection/harness/gen_menu_assets.py - never "
           "hand-edit\n"]
    for name, text in MENU_LABELS.items():
        img = render(text, SIZES.get(name, 40))
        data = img.tobytes()
        out.append(f"static const int MVMENU_{name}_W = {img.width};")
        out.append(f"static const int MVMENU_{name}_H = {img.height};")
        rows = [", ".join(str(b) for b in data[i:i + 24])
                for i in range(0, len(data), 24)]
        out.append(f"static const unsigned char MVMENU_{name}[] = {{\n\t"
                   + ",\n\t".join(rows) + " };\n")
    body = "\n".join(out)
    with open(HEADER, "w", newline="\n") as f:
        f.write(body)
    print(f"wrote {HEADER} ({len(body)} bytes)")


if __name__ == "__main__":
    sys.exit(main())
